### ISSUE TITLE
Future direction?

### ISSUE THREAD

**Issue by Tokazama** [timholy/ANTsRegistration.jl#1]
Is most of ANTs functionality now easily implemented in Images.jl or would it be worth getting a julia interface to the command line code for ANTs working still?

**Comment by timholy** [comment]
Still worth it; it's a really good registration framework. That said I am working on something pure-Julia that *will* be better (or I will die trying...I'm betting on die, currently :smile:). Image registration is a surprisingly finicky task.

Are you saying this is broken? Or just wondering whether this is worth trying?

**Comment by Tokazama** [comment]
I just wanted to know if it was worth trying to use it and contributing (since I couldn't immediately `add AntsRegistration`). I use ANTs a lot because it has great results but I'd like a Julia based interface for image registration. That being said, it would be amazing if there was something of comparable quality in Julia.

**Comment by timholy** [comment]
It's not registered but you can `add url` it. I think this eases some of the pain of working with ANTs, but I should say that my own usage of it has mostly been limited to "comparison" rather than "daily workhorse". You may know much more about it than me, so I would welcome your contributions.

**Comment by Tokazama** [comment]
Then I'll probably start looking at it after I finish up some papers these next few weeks. With your blessing I'll probably add `N4BiasFieldCorrection` too, as it's a pretty critical component of the registration process. The only other critical step preceding registration is brain extraction, but that could probably be built around some fairly basic methods once some sort of registration framework is in place.

**Comment by IanButterworth** [comment]
@timholy I'm intrigued by your secret pure-julia image registration project.. How's that going?

Also, I made a suggested PR for building ANTs automatically with BinaryProvider #4.

**Comment by timholy** [comment]
Much, but not all, of our code is publicly visible now. See https://github.com/HolyLab and specifically HolyLabRegistry to get access. There are still almost no "user-level" docs (lots and lots of docstrings though) and the top-level packages are not yet registered.

**Comment by IanButterworth** [comment]
@timholy from my initial impressions with RegisterQD I'm really excited. Thanks so much

**Comment by timholy** [comment]
That's great! Folks in my lab will be pleased to hear it.

**Comment by timholy** [comment]
I am curious, what registration problem are you tackling?

**Comment by IanButterworth** [comment]
Stabilization of in-vivo microscopy videos. Hoping for accurate and fast, hence my excitement for ANTs-competitive accuracy natively in Julia!

**Comment by timholy** [comment]
For those curious, the ANTs-like Julia registration framework is [BlockRegistration](https://github.com/HolyLab/BlockRegistration.jl), and it even has docs. You can also do shift-registration with `register_translate` from [RegisterMismatch](https://github.com/HolyLab/RegisterMismatch.jl), which is one component of the BlockRegistration "suite." And as linked above, RegisterQD is for global rigid and affine registration.
